name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

env:
  CI: "true"
  PHP_CS_FIXER_IGNORE_ENV: "true"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  sdk:
    name: SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.2", "8.3", "8.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
